/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiMockStorageRouteImport } from './routes/api/mock-storage'
import { Route as ApiMockDbRouteImport } from './routes/api/mock-db'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultRouteImport } from './routes/_authenticated/consult'
import { Route as AuthenticatedCalculatorRouteImport } from './routes/_authenticated/calculator'
import { Route as AuthenticatedScanProductRouteImport } from './routes/_authenticated/scan.product'
import { Route as AuthenticatedScanMealRouteImport } from './routes/_authenticated/scan.meal'
import { Route as ApiPublicHooksWipeMonthlyPhotosRouteImport } from './routes/api/public/hooks/wipe-monthly-photos'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockStorageRoute = ApiMockStorageRouteImport.update({
  id: '/api/mock-storage',
  path: '/api/mock-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockDbRoute = ApiMockDbRouteImport.update({
  id: '/api/mock-db',
  path: '/api/mock-db',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultRoute = AuthenticatedConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculatorRoute = AuthenticatedCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScanProductRoute =
  AuthenticatedScanProductRouteImport.update({
    id: '/scan/product',
    path: '/scan/product',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScanMealRoute = AuthenticatedScanMealRouteImport.update({
  id: '/scan/meal',
  path: '/scan/meal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksWipeMonthlyPhotosRoute =
  ApiPublicHooksWipeMonthlyPhotosRouteImport.update({
    id: '/api/public/hooks/wipe-monthly-photos',
    path: '/api/public/hooks/wipe-monthly-photos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/consult': typeof AuthenticatedConsultRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/mock-db': typeof ApiMockDbRoute
  '/api/mock-storage': typeof ApiMockStorageRoute
  '/scan/meal': typeof AuthenticatedScanMealRoute
  '/scan/product': typeof AuthenticatedScanProductRoute
  '/api/public/hooks/wipe-monthly-photos': typeof ApiPublicHooksWipeMonthlyPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calculator': typeof AuthenticatedCalculatorRoute
  '/consult': typeof AuthenticatedConsultRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/mock-db': typeof ApiMockDbRoute
  '/api/mock-storage': typeof ApiMockStorageRoute
  '/scan/meal': typeof AuthenticatedScanMealRoute
  '/scan/product': typeof AuthenticatedScanProductRoute
  '/api/public/hooks/wipe-monthly-photos': typeof ApiPublicHooksWipeMonthlyPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/calculator': typeof AuthenticatedCalculatorRoute
  '/_authenticated/consult': typeof AuthenticatedConsultRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/mock-db': typeof ApiMockDbRoute
  '/api/mock-storage': typeof ApiMockStorageRoute
  '/_authenticated/scan/meal': typeof AuthenticatedScanMealRoute
  '/_authenticated/scan/product': typeof AuthenticatedScanProductRoute
  '/api/public/hooks/wipe-monthly-photos': typeof ApiPublicHooksWipeMonthlyPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/calculator'
    | '/consult'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/api/mock-db'
    | '/api/mock-storage'
    | '/scan/meal'
    | '/scan/product'
    | '/api/public/hooks/wipe-monthly-photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/calculator'
    | '/consult'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/api/mock-db'
    | '/api/mock-storage'
    | '/scan/meal'
    | '/scan/product'
    | '/api/public/hooks/wipe-monthly-photos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/calculator'
    | '/_authenticated/consult'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/settings'
    | '/api/mock-db'
    | '/api/mock-storage'
    | '/_authenticated/scan/meal'
    | '/_authenticated/scan/product'
    | '/api/public/hooks/wipe-monthly-photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiMockDbRoute: typeof ApiMockDbRoute
  ApiMockStorageRoute: typeof ApiMockStorageRoute
  ApiPublicHooksWipeMonthlyPhotosRoute: typeof ApiPublicHooksWipeMonthlyPhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock-storage': {
      id: '/api/mock-storage'
      path: '/api/mock-storage'
      fullPath: '/api/mock-storage'
      preLoaderRoute: typeof ApiMockStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock-db': {
      id: '/api/mock-db'
      path: '/api/mock-db'
      fullPath: '/api/mock-db'
      preLoaderRoute: typeof ApiMockDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consult': {
      id: '/_authenticated/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof AuthenticatedConsultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculator': {
      id: '/_authenticated/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof AuthenticatedCalculatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan/product': {
      id: '/_authenticated/scan/product'
      path: '/scan/product'
      fullPath: '/scan/product'
      preLoaderRoute: typeof AuthenticatedScanProductRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scan/meal': {
      id: '/_authenticated/scan/meal'
      path: '/scan/meal'
      fullPath: '/scan/meal'
      preLoaderRoute: typeof AuthenticatedScanMealRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/wipe-monthly-photos': {
      id: '/api/public/hooks/wipe-monthly-photos'
      path: '/api/public/hooks/wipe-monthly-photos'
      fullPath: '/api/public/hooks/wipe-monthly-photos'
      preLoaderRoute: typeof ApiPublicHooksWipeMonthlyPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalculatorRoute: typeof AuthenticatedCalculatorRoute
  AuthenticatedConsultRoute: typeof AuthenticatedConsultRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedScanMealRoute: typeof AuthenticatedScanMealRoute
  AuthenticatedScanProductRoute: typeof AuthenticatedScanProductRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalculatorRoute: AuthenticatedCalculatorRoute,
  AuthenticatedConsultRoute: AuthenticatedConsultRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedScanMealRoute: AuthenticatedScanMealRoute,
  AuthenticatedScanProductRoute: AuthenticatedScanProductRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiMockDbRoute: ApiMockDbRoute,
  ApiMockStorageRoute: ApiMockStorageRoute,
  ApiPublicHooksWipeMonthlyPhotosRoute: ApiPublicHooksWipeMonthlyPhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
